hero_image: photos/penny_fan.jpg
hero_position: center center
mobile_hero_image: photos/croatia.jpg
mobile_hero_position: center center


theme:
  # text_color: '#404040'
  # primary_color: '#d98560'
  secondary_color: '#bdc99d'
  #accent_color: '#fff'
  background_color: '#fff' 

rsvp:
  use_code: true
  code: 100824
  code_md5: d868f520adb4aaa159c339a52df7e449
  post_address: https://script.google.com/macros/s/AKfycbwIOSsjWXYWHzq-LmqvU0vqFS3Clty4776EEZnl1DCFg8CLwL2GxysUOwDGos7J9rhh/exec
  api_key: 
  code_location: You'll find this code on the back of your paper copy of the RSVP invite. 
  yes_text: I'll be there
  no_text: I can't make it
  no_extra_guests_message: As much as we would love to have everyone, please only include guests that were listed on your invitation
  submit_text: RSVP
  cancel_text: Cancel
  yes_modal_title: Thank You!
  no_modal_title: Thank You!
  yes_modal_body: We're glad that you've decided to celebrate with us on our wedding day!
  no_modal_body: We really wish you could have made it, but we still love you. <span class="fa fa-heart"></span>
  sms_followup_text: You'll receive a email confirmation shortly.
  # Comment these out to disable
  song_text: What songs will get you dancing?
  leave_a_message_text: Leave a message for the bride and groom.
  dietary_requirements: Do you have any dietary requirements?